config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :libraries

  resources :books, only: %i[index show create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :library, class_name: "Library", foreign_key: "library_id"

  validates :title, presence: true
  validates :author, presence: true
end

app/models/library.rb
class Library < ApplicationRecord
    has_many :books, class_name: "Book", foreign_key: "book_id"

    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @books = Book.all

    render json: @books
  end

  def show
    @book = Book.find(params[:id])

    render json: @book
  end

  def create
    @book = Book.new(permitted_params)

    if @book.save
      render json: { success: true }, status: :created
    else
      render json: {}, status: :bad_request
    end
  end

  private

  def permitted_params
    params.require(:book).permit(:title, :author, :library_id)
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: %i[ show edit update destroy ]

  # GET /libraries or /libraries.json
  def index
    @libraries = Library.all
  end

  # GET /libraries/1 or /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries or /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: "Library was successfully created." }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1 or /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: "Library was successfully updated." }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1 or /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url, notice: "Library was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def library_params
      params.fetch(:library, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/libraries/_form.html.erb
<%= form_with(model: library, local: true) do |form| %>
  <% if library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
      <% library.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<h1>Editing Library</h1>

<%= render 'form', library: @library %>

<%= link_to 'Show', @library %> |
<%= link_to 'Back', libraries_path %>

app/views/libraries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Libraries</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libraries.each do |library| %>
      <tr>
        <td><%= link_to 'Show', library %></td>
        <td><%= link_to 'Edit', edit_library_path(library) %></td>
        <td><%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Library', new_library_path %>

app/views/libraries/new.html.erb
<h1>New Library</h1>

<%= render 'form', library: @library %>

<%= link_to 'Back', libraries_path %>

app/views/libraries/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_library_path(@library) %> |
<%= link_to 'Back', libraries_path %>